version: "3.7"

services:
    # image project
    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - minha_rede

    # nginx
    nginxapi:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "9999:81"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - minha_rede
        security_opt:
            - "label:disable"

    # db mysql
    dbapi:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: api
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - minha_rede

networks:
  minha_rede:
    external: true

